openapi: 3.0.3
info:
  title: ED&FMan Custom API
  version: '1.7'
  description: |
    **Release notes (5th October 2026.)**

    ## New Endpoints

    - Inventory **Lots Create**: Create Lots, [Link](#/Inventory/CreateLots)
    - Inventory **Lots Update**: Update Lots, [Link](#/Inventory/UpdateLots)
    - Inventory **Lots Delete**: Delete Lots, [Link](#/Inventory/DeleteLots)
    - Inventory **Logistics Plan Create**: Create Logistics Plan, [Link](#/Inventory/CreateLogisticsPlan)
servers:
  - url: https://{yourServer}:5720
    variables:
      yourServer:
        default: localhost
        description: Hostname or IP address of the ITAS server
  - url: http://{yourServer}:4720
    variables:
      yourServer:
        default: localhost
        description: Hostname or IP address of the ITAS server
security:
  - BearerAuth: []
paths:
  /Contracts/{TradingEntityId}/Traffic/NetAndGrossWeights/{PhysicalTradeId}:
    patch:
      tags:
      - Contract-Physical
      summary: Update Net and Gross Weights
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetGrossWeight UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      - name: PhysicalTradeId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetGrossWeightUpdate'
  /ElectronicOrderBook/BrokerData:
    post:
      tags:
      - Electronic Order Book
      summary: Create Broker Data
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrokerData CreateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrokerDataCreate'
  /ElectronicOrderBook/BrokerData/{OrderId}:
    patch:
      tags:
      - Electronic Order Book
      summary: Update Broker Data
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderId UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: OrderId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrokerDataUpdate'
    delete:
      tags:
      - Electronic Order Book
      summary: Delete Broker Data
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderId DeleteResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: OrderId
        in: path
        required: true
        schema:
          type: string
  /ElectronicOrderBook/WebIceData:
    post:
      tags:
      - Electronic Order Book
      summary: Create WebIce Data
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebIceData CreateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrokerDataCreate'
  /ElectronicOrderBook/WebIceData/{OrderId}:
    patch:
      tags:
      - Electronic Order Book
      summary: Update WebIce Data
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderId UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: OrderId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrokerDataUpdate'
    delete:
      tags:
      - Electronic Order Book
      summary: Delete WebIce Data
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderId DeleteResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: OrderId
        in: path
        required: true
        schema:
          type: string
  /Invoicing/{TradingEntityId}/Trade/DischargeWeights:
    post:
      tags:
      - Invoicing
      summary: Create Discharge Weights
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DischargeWeights CreateResult'
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DischargeWeights UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DischargeWeightsRequest'
  /Invoicing/{TradingEntityId}/Cotton/InvoiceStage:
    post:
      tags:
      - Invoicing
      summary: Create Invoice Staging Records
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceStage CreateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceStageRequest'
  /Inventory/{TradingEntityId}/Grouping/CreateBaleGrouping:
    post:
      tags:
      - Inventory
      summary: Create Bale Grouping
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaleGrouping CreateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaleGroupingRequest'
  /Inventory/{TradingEntityId}/Grouping/UpdateBaleGrouping/{GroupId}:
    patch:
      tags:
      - Inventory
      summary: Update Bale Grouping
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaleGrouping UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      - name: GroupId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaleGroupingUpdateRequest'
  /Inventory/{TradingEntityId}/Grouping/RemoveBaleGrouping/{GroupId}:
    delete:
      tags:
      - Inventory
      summary: Remove Bale Grouping
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaleGrouping DeleteResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      - name: GroupId
        in: path
        required: true
        schema:
          type: string
  /Inventory/{TradingEntityId}/LogisticsMovement/{GroupId}/{Uniqueness}:
    patch:
      tags:
      - Inventory
      summary: Update Logistics Movement
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogisticsMovement UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      - name: GroupId
        in: path
        required: true
        schema:
          type: string
      - name: Uniqueness
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogisticsMovement Update'
  /Inventory/{TradingEntityId}/Grouping/CreateLogisticsPlan:
    post:
      operationId: CreateLogisticsPlan
      tags:
      - Inventory
      summary: Create Logistics Plan
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogisticsPlanResponse'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogisticsPlanRequest'
  /Inventory/{TradingEntityId}/Lots/CreateLots:
    post:
      operationId: CreateLots
      tags:
      - Inventory
      summary: Create Lots
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lots CreateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LotRequest'
  /Inventory/{TradingEntityId}/Lots/UpdateLots:
    patch:
      operationId: UpdateLots
      tags:
      - Inventory
      summary: Update Lots
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lots UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LotRequest'
  /Inventory/{TradingEntityId}/Lots/DeleteLots:
    delete:
      operationId: DeleteLots
      tags:
      - Inventory
      summary: Delete Lots
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lots DeleteResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LotRequestDelete'
  /Stocks/{TradingEntityId}/Instructions/CreateInstructionSheet/{PhysicalTradeId}/{ReleaseId}:
    put:
      tags:
      - Stocks
      summary: Create Instruction Sheet
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructionSheet UpdateResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      - name: PhysicalTradeId
        in: path
        required: true
        schema:
          type: string
      - name: ReleaseId
        in: path
        required: true
        schema:
          type: string
  /Stocks/{TradingEntityId}/Instructions/DeleteInstructionSheet/{PhysicalTradeId}/{ReleaseId}:
    delete:
      tags:
      - Stocks
      summary: Delete Instruction Sheet
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructionSheet DeleteResult'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400 Response'
        '404':
          description: '404'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404 Response'
        '405':
          description: '405'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/405 Response'
      parameters:
      - name: TradingEntityId
        in: path
        required: true
        schema:
          type: string
      - name: PhysicalTradeId
        in: path
        required: true
        schema:
          type: string
      - name: ReleaseId
        in: path
        required: true
        schema:
          type: string
  /Controller:
    get:
      tags:
      - Data Object Definitions
      summary: Controller
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ControllerInput1'
  /DischargeWeight:
    get:
      tags:
      - Data Object Definitions
      summary: Discharge Weight
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DischargeWeightsResponse1'
  /InvoiceStageLeg:
    get:
      tags:
      - Data Object Definitions
      summary: Invoice Stage Leg
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceStageLeg'
  /Lot:
    get:
      tags:
      - Data Object Definitions
      summary: Lot
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lot'
  /Shipping:
    get:
      tags:
      - Data Object Definitions
      summary: Shipping
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipping'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    200 SuccessResponse:
      type: object
      properties:
        Value:
          type: string
          example: Success
    200 UpdateResponse:
      type: object
      properties:
        Value:
          type: string
          example: Updated
    200 DeletedResponse:
      type: object
      properties:
        Value:
          type: string
          example: Deleted
    200 AuthoriseResponse:
      type: object
      properties:
        Value:
          type: string
          example: Authorised
    201 CreateResponse:
      type: object
      properties:
        Value:
          type: string
          example: Created
    201 CreateMessages:
      type: object
      properties:
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/201 ErrorMessageDetail'
    201 ErrorMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Warning
        Message:
          type: string
          example: 'API5084 - API : {fieldName} has a {fieldName} of {value}.'
    201 CreateBllMessages:
      type: object
      properties:
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/201 ErrorBllMessageDetail'
    201 ErrorBllMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Warning
        Message:
          type: string
          example: 'API5084 - API : {fieldName} has a {fieldName} of {value}.'
    400 Response:
      type: object
      properties:
        Response:
          type: object
          properties:
            Value:
              type: string
              example: 400 Bad Request
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/400 ErrorMessageDetail'
    400 ErrorMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Error
        Message:
          type: string
          example: 'API5058 - Data : The mandatory field {fieldName} was missing in the request body.'
    400 BadPropertyResponse:
      type: object
      properties:
        Response:
          type: object
          properties:
            Value:
              type: string
              example: 400 Bad Request
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/400 BadPropertyErrorMessageDetail'
    400 BadPropertyErrorMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Error
        Message:
          type: string
          example: 'API5074 - API : The value sent in the querystring variable {Property} is not allowed.'
    400 BadReadResponse:
      type: object
      properties:
        Response:
          type: object
          properties:
            Value:
              type: string
              example: 400 Bad Request
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/400 BadReadErrorMessageDetail'
    400 BadReadErrorMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Error
        Message:
          type: string
          example: 'API5075 - API : The value sent in the querystring is not allowed.'
    400 WarningMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Warning
        Message:
          type: string
          example: 'API50xx - Data : The field {fieldName} was not found.'
    400 InfoMessageDetail:
      type: object
      properties:
        Severity:
          type: string
          example: Information
        Message:
          type: string
          example: 'API50xx - Data : Now create xyz.'
    404 Response:
      type: object
      properties:
        Response:
          type: object
          properties:
            Value:
              type: string
              example: 404 Not Found
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/404 ErrorMessageDetailMessage'
    404 ErrorMessageDetailMessage:
      type: object
      properties:
        Severity:
          type: string
          example: Warning
        Message:
          type: string
          example: 'API5068 - Data : No records found.'
    405 Response:
      type: object
      properties:
        Response:
          type: object
          properties:
            Value:
              type: string
              example: 405 Method Not Allowed
        Messages:
          type: array
          items:
            $ref: '#/components/schemas/405 MethodNotAllowedMessage'
    405 MethodNotAllowedMessage:
      type: object
      properties:
        Severity:
          type: string
          example: Error
        Message:
          type: string
          example: 'API5077 - API : That method is not supported, please check the ITAS API documentation.'
    accessToken:
      type: object
      properties: {}
    BaleGroupingRequest:
      type: object
      properties:
        GroupType:
          type: string
          example: Logistics
        GroupSubTypeCode:
          type: string
          example: SHORTS
        GroupDescription:
          type: string
          example: Short Bales
        IsStopWeights:
          type: boolean
          example: true
        InventoryIds:
          type: array
          items:
            type: integer
          example:
            - 150
            - 151
        AllocatedSaleCode:
          type: string
          example: ''
        MarksStyle:
          type: string
          example: Manual
        Mark:
          type: string
          example: ACGT
        Prefix:
          type: string
          example: ''
        NewRecap:
          type: boolean
          example: true
        RecapPrefix:
          type: string
          example: C1
        RecapMark:
          type: string
          example: MEMPHIS
        RecapDescription:
          type: string
          example: Grade 1 Memphis
        RecapStatus:
          type: string
          example: Valid
    BaleGroupingUpdateRequest:
      type: object
      properties:
        GroupId:
          type: number
          example: 50
        GroupDescription:
          type: string
          example: Short Bales
        MarksStyle:
          type: string
          example: Manual
        Mark:
          type: string
          example: ACGT
        Prefix:
          type: string
          example: ''
        NewRecap:
          type: boolean
          example: true
        RecapPrefix:
          type: string
          example: C1
        RecapMark:
          type: string
          example: MEMPHIS
        RecapDescription:
          type: string
          example: Grade 1 Memphis
        RecapStatus:
          type: string
          example: Valid
    BaleGroupingInventoryId1:
      type: object
      properties:
        InventoryId:
          type: number
          example: 150
    BaleGroupingInventoryId2:
      type: object
      properties:
        InventoryId:
          type: number
          example: 151
    BaleGroupingResponse:
      type: object
      properties:
        GroupId:
          type: number
          example: 50
    BrokerDataCreate:
      type: object
      properties:
        OrderId:
          type: number
          example: 1
        SerialNo:
          type: number
          example: 123
        TradeDate:
          type: string
          example: '2015-07-01T00:00:00Z'
        AccountCode:
          type: string
          example: ABCDEF.P
        TradeCodeId:
          type: string
          example: AA
        DepartmentCode:
          type: string
          example: '5100'
        InstrumentCode:
          type: string
          example: NY11
        PromptDate:
          type: string
          example: '2015-07-01'
        Instruction:
          type: boolean
          example: true
        OptionType:
          type: string
          example: Call
        OptionSeries:
          type: number
          example: 123
        BuySell:
          type: string
          example: Buy
        Lots:
          type: number
          example: 100
        PhysicalTradeCode:
          type: string
          example: P00007.003
        BrokerCode:
          type: string
          example: ABCDEF.P
        Price:
          type: number
          example: 12345
        FloorBrokerCode:
          type: string
          example: ABCDEF.P
        TraderCode:
          type: string
          example: TT
        Memo:
          type: string
          example: AB CD EF
        StrategyCode:
          type: string
          example: P1
        StrategyGroupCode:
          type: string
          example: PORT
        Memo2:
          type: string
          example: GHI JKL
        ExternalSerial:
          type: string
          example: ABCD
        CommissionCodeRateCode:
          type: number
          example: 2
        BrokerPrice:
          type: number
          example: 20.2
        BuybackReference:
          type: number
          example: 1002
        ClientOrBroker:
          type: string
          example: Client
        CommissionCurrencyCode:
          type: string
          example: GBP
        CommissionType:
          type: string
          example: Percentage
        CommissionRate:
          type: number
          example: 12.5
        CounterpartyCode:
          type: string
          example: COUNT.P
        DeclaredPrice:
          type: number
          example: 53.1
        ExchangeCode:
          type: string
          example: NYFE
        InventoryHedgeType:
          type: string
          example: '2'
        IsPhysicalFix:
          type: string
          example: 'true'
        OTCBrokerCode:
          type: string
          example: OTCB.T
        OTCBrokerCommissionCurrencyCode:
          type: string
          example: USD
        OTCCommission:
          type: number
          example: 2.4
        SecondBrokerCommissionCurrencyCode:
          type: string
          example: GBP
        TradeTime:
          type: string
          example: '15:25'
        TradingEntityId:
          type: string
          example: DT
    BrokerDataUpdate:
      type: object
      properties:
        OrderId:
          type: number
          example: 1
        SerialNo:
          type: number
          example: 123
        TradeDate:
          type: string
          example: '2015-07-01T00:00:00Z'
        AccountCode:
          type: string
          example: ABCDEF.P
        TradeCodeId:
          type: string
          example: AA
        DepartmentCode:
          type: string
          example: '5100'
        InstrumentCode:
          type: string
          example: NY11
        PromptDate:
          type: string
          example: '2015-07-01'
        Instruction:
          type: boolean
          example: true
        OptionType:
          type: string
          example: Call
        OptionSeries:
          type: number
          example: 123
        BuySell:
          type: string
          example: Buy
        Lots:
          type: number
          example: 100
        PhysicalTradeCode:
          type: string
          example: P00007.003
        BrokerCode:
          type: string
          example: ABCDEF.P
        Price:
          type: number
          example: 12345
        FloorBrokerCode:
          type: string
          example: ABCDEF.P
        TraderCode:
          type: string
          example: TT
        Memo:
          type: string
          example: AB CD EF
        StrategyCode:
          type: string
          example: P1
        StrategyGroupCode:
          type: string
          example: PORT
        Memo2:
          type: string
          example: GHI JKL
        ExternalSerial:
          type: string
          example: ABCD
        CommissionCodeRateCode:
          type: number
          example: 2
        BrokerPrice:
          type: number
          example: 20.2
        BuybackReference:
          type: number
          example: 1002
        ClientOrBroker:
          type: string
          example: Client
        CommissionCurrencyCode:
          type: string
          example: GBP
        CommissionType:
          type: string
          example: Percentage
        CommissionRate:
          type: number
          example: 12.5
        CounterpartyCode:
          type: string
          example: COUNT.P
        DeclaredPrice:
          type: number
          example: 53.1
        ExchangeCode:
          type: string
          example: NYFE
        InventoryHedgeType:
          type: string
          example: '2'
        IsPhysicalFix:
          type: string
          example: 'true'
        OTCBrokerCode:
          type: string
          example: OTCB.T
        OTCBrokerCommissionCurrencyCode:
          type: string
          example: USD
        OTCCommission:
          type: number
          example: 2.4
        SecondBrokerCommissionCurrencyCode:
          type: string
          example: GBP
        TradeTime:
          type: string
          example: '15:25'
        TradingEntityId:
          type: string
          example: DT
    ControllerInput1:
      type: object
      properties:
        LandingSurveyorCode:
          type: string
          example: SURV1.P
        NetWeight:
          type: number
          example: 1000
        WeightDate:
          type: string
          example: '2026-09-12T00:00:00Z'
      required:
      - LandingSurveyorCode
      - NetWeight
      - WeightDate
    ControllerInput2:
      type: object
      properties:
        LandingSurveyorCode:
          type: string
          example: SURV2.P
        NetWeight:
          type: number
          example: 900
        WeightDate:
          type: string
          example: '2026-08-25T00:00:00Z'
      required:
      - LandingSurveyorCode
      - NetWeight
      - WeightDate
    DischargeWeightsRequest:
      type: object
      properties:
        PhysicalTradeId:
          type: string
          example: S00001.001
        LandingReportDate:
          type: string
          example: '2026-08-28T00:00:00Z'
        ControllerReference:
          type: string
          example: CONTROL01
        FirstController:
          $ref: '#/components/schemas/ControllerInput1'
        SecondController:
          $ref: '#/components/schemas/ControllerInput2'
      required:
      - PhysicalTradeId
      - LandingReportDate
      - ControllerReference
      - FirstController
    DischargeWeightsResponse1:
      type: object
      properties:
        PhysicalTradeId:
          type: string
          example: S00001.001
        WeightCode:
          type: string
          example: LBS
        GrossWeight:
          type: number
          example: 1100
        RecordType:
          type: string
          example: Discharge
    DischargeWeightsResponse2:
      type: object
      properties:
        PhysicalTradeId:
          type: string
          example: S00001.001
        WeightCode:
          type: string
          example: LBS
        GrossWeight:
          type: number
          example: 1000
        RecordType:
          type: string
          example: NetLandedTwo
    DischargeWeightsResponse:
      type: object
      properties:
        DischargeWeights:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/DischargeWeightsResponse1'
            - $ref: '#/components/schemas/DischargeWeightsResponse2'
          example:
            - PhysicalTradeId: S00001.001
              WeightCode: LBS
              GrossWeight: 1100
              RecordType: Discharge
            - PhysicalTradeId: S00001.001
              WeightCode: LBS
              GrossWeight: 1000
              RecordType: NetLandedTwo
    InvoiceStageLeg:
      type: object
      properties:
        GroupNumber:
          type: number
          example: 1
        HaulId:
          type: number
          example: 101
        CostCode:
          type: string
          example: CC-100
        PercentActualised:
          type: number
          example: 100
        InvoiceValue:
          type: number
          example: 110
        VatCode:
          type: string
          example: S1
        NominalAccountCode:
          type: string
          example: NOM-100
        ExpenseCode:
          type: string
          example: EXP- 10
        Narrative:
          type: string
          example: Invoice Leg 1
    InvoiceStageLeg2:
      type: object
      properties:
        GroupNumber:
          type: number
          example: 2
        HaulId:
          type: number
          example: 102
        CostCode:
          type: string
          example: CC-200
        PercentActualised:
          type: number
          example: 100
        InvoiceValue:
          type: number
          example: 120
        VatCode:
          type: string
          example: S1
        NominalAccountCode:
          type: string
          example: NOM-200
        ExpenseCode:
          type: string
          example: EXP- 20
        Narrative:
          type: string
          example: Invoice Leg 2
    InvoiceStageRequest:
      type: object
      properties:
        DocumentDate:
          type: string
          example: '2026-08-12T00:00:00Z'
        ValueDate:
          type: string
          example: '2026-09-12T00:00:00Z'
        Type:
          type: string
          example: Warehouse
        SupplierCode:
          type: string
          example: WARH01
        PaymentTermsCode:
          type: string
          example: NET30
        ClientReference:
          type: string
          example: REF-2025-001
        DocumentFile:
          type: string
          example: ZG9jMQ==
        DocumentName:
          type: string
          example: doc1.pdf
        Legs:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/InvoiceStageLeg'
            - $ref: '#/components/schemas/InvoiceStageLeg2'
          example:
            - GroupNumber: 1
              HaulId: 101
              CostCode: CC-100
              PercentActualised: 100
              InvoiceValue: 110
              VatCode: S1
              NominalAccountCode: NOM-100
              ExpenseCode: EXP- 10
              Narrative: Invoice Leg 1
            - GroupNumber: 2
              HaulId: 102
              CostCode: CC-200
              PercentActualised: 100
              InvoiceValue: 120
              VatCode: S1
              NominalAccountCode: NOM-200
              ExpenseCode: EXP- 20
              Narrative: Invoice Leg 2
      required:
      - DocumentDate
      - ValueDate
    InvoiceStageResponse:
      type: object
      properties:
        TransactionId:
          type: number
          example: 10
    LogisticsPlanRequest:
      type: object
      properties:
        GroupIds:
          type: array
          items:
            type: integer
          example:
            - 152116
            - 152117
            - 152118
    LogisticsPlanResponse:
      type: object
      properties:
        PlanId:
          type: number
          example: 2456
    LogisticsMovement Update:
      type: object
      properties:
        GroupId:
          type: number
          example: 1515
        Uniqueness:
          type: number
          example: 4
        RequestedLoadDate:
          type: string
          example: '2026-08-12T00:00:00Z'
        ShipmentOrderRequested:
          type: boolean
          example: true
        DestinationWarehouse:
          type: string
          example: 054205.P
    Lot:
      type: object
      properties:
        InventoryId:
          type: number
          example: 123
        WarehouseDate:
          type: string
          example: '2026-09-30T00:00:00Z'
        WarehouseReference:
          type: string
          example: '0146645'
        FuturesLotNumber:
          type: string
          example: '10'
        BillOfLadingNumber:
          type: string
          example: '9785'
        FarmTract:
          type: string
          example: Tract 1
        GrossWeight:
          type: number
          example: 25000.5
        Tare:
          type: number
          example: 500
        NetWeight:
          type: number
          example: 24500.5
        Quantity:
          type: number
          example: 100
        WeightCode:
          type: string
          example: MT
        ShippingDate:
          type: string
          example: '2026-09-30T00:00:00Z'
        PurchaseContractCode:
          type: string
          example: P00001.000
        PurchaseGrade:
          type: string
          example: GM
        StapleLength32ndsInch:
          type: number
          example: 35
        StapleLength100thsInch:
          type: number
          example: 1.07
        Micronaire:
          type: number
          example: 4.2
        Strength:
          type: number
          example: 30.5
        ShortFibreContent:
          type: number
          example: 5.2
        UniformityInLength:
          type: number
          example: 82.5
        Extraneous:
          type: string
          example: '01'
        LeafGrade:
          type: string
          example: '2'
        ColourGrade:
          type: string
          example: '31'
        Comments:
          type: string
          example: Example cotton lot
        InstColourGradeGreyness:
          type: number
          example: 41
        Shipping:
          $ref: '#/components/schemas/Shipping'
    LotRequest:
      type: object
      properties:
        VesselGroup:
          type: string
          example: VESGRP
        NewVesselGroup:
          type: boolean
          example: true
        Lots:
          type: array
          items:
            $ref: '#/components/schemas/Lot'
    LotRequestDelete:
      type: object
      properties:
        InventoryIds:
          type: array
          items:
            type: number
          example:
            - 123
            - 456
            - 789
    NetGrossWeightResponseP:
      type: object
      properties:
        PhysicalTradeId:
          type: string
          example: P00001.000
        UnitOfMeasurementCode:
          type: string
          example: MT
        Quantity:
          type: number
          example: 20
    NetGrossWeightResponseS:
      type: object
      properties:
        PhysicalTradeId:
          type: string
          example: S00001.000
        UnitOfMeasurementCode:
          type: string
          example: MT
        Quantity:
          type: number
          example: 20
    NetGrossWeightUpdate:
      type: object
      properties:
        PhysicalTradeId:
          type: string
          example: P00001.000
        GrossWeight:
          type: number
          example: 21
        Quantity:
          type: number
          example: 20
    Shipping:
      type: object
      properties:
        VesselReference:
          type: string
          example: Vessel 001
        JourneyNumber:
          type: string
          example: JRN-001
        OrderStatusCode:
          type: string
          example: D
        OrderStatusDate:
          type: string
          example: '2026-10-25T00:00:00Z'
        EstimatedArrivalDate:
          type: string
          example: '2026-10-30T00:00:00Z'
        PortOfDestinationCode:
          type: string
          example: AACHEN
        ShippingLineCode:
          type: string
          example: MSC.P
        EstimatedShipmentDate:
          type: string
          example: '2026-09-30T00:00:00Z'
    NetGrossWeight UpdateResult:
      type: object
      properties:
        Data:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/NetGrossWeightResponseP'
            - $ref: '#/components/schemas/NetGrossWeightResponseS'
          example:
            - PhysicalTradeId: P00001.000
              UnitOfMeasurementCode: MT
              Quantity: 20
            - PhysicalTradeId: S00001.000
              UnitOfMeasurementCode: MT
              Quantity: 20
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    BrokerData CreateResult:
      type: object
      properties:
        Data:
          type: object
          properties:
            BrokerDataId:
              type: number
              example: 1
            OrderId:
              type: number
              example: 1
        Response:
          $ref: '#/components/schemas/201 CreateResponse'
    WebIceData CreateResult:
      type: object
      properties:
        Data:
          type: object
          properties:
            WebIceDataId:
              type: number
              example: 1
            OrderId:
              type: number
              example: 1
        Response:
          $ref: '#/components/schemas/201 CreateResponse'
    OrderIdData:
      type: object
      properties:
        OrderId:
          type: number
          example: 1
    OrderId UpdateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/OrderIdData'
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    OrderId DeleteResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/OrderIdData'
        Response:
          $ref: '#/components/schemas/200 DeletedResponse'
    DischargeWeights CreateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/DischargeWeightsResponse'
        Response:
          $ref: '#/components/schemas/201 CreateResponse'
    DischargeWeights UpdateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/DischargeWeightsResponse'
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    InvoiceStage CreateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/InvoiceStageResponse'
        Response:
          $ref: '#/components/schemas/201 CreateResponse'
    BaleGrouping CreateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/BaleGroupingResponse'
        Response:
          $ref: '#/components/schemas/201 CreateResponse'
    BaleGrouping UpdateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/BaleGroupingResponse'
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    BaleGrouping DeleteResult:
      type: object
      properties:
        Data:
          type: object
          properties:
            GroupId:
              type: number
              example: 150
        Response:
          $ref: '#/components/schemas/200 DeletedResponse'
    LogisticsMovement UpdateResult:
      type: object
      properties:
        Data:
          type: object
          properties:
            GroupId:
              type: number
              example: 1515
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    LotsResponseData:
      type: object
      properties:
        GroupingId:
          type: number
          example: 1
        ContractSplits:
          type: array
          items:
            type: string
          example:
            - P00001.001
            - P00001.002
        InventoryIds:
          type: array
          items:
            type: number
          example:
            - 123
            - 234
    Lots CreateResult:
      type: object
      properties:
        GroupingId:
          type: number
          example: 1
        ContractSplits:
          type: array
          items:
            type: string
          example:
            - P00001.001
            - P00001.002
        InventoryIds:
          type: array
          items:
            type: number
          example:
            - 123
            - 234
        Response:
          $ref: '#/components/schemas/201 CreateResponse'
    Lots UpdateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/LotsResponseData'
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    Lots DeleteResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/LotsResponseData'
        Response:
          $ref: '#/components/schemas/200 DeletedResponse'
    InstructionSheetData:
      type: object
      properties:
        PhyscialTradeId:
          type: string
          example: P00001.001
        ReleaseId:
          type: number
          example: 123
    InstructionSheet UpdateResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/InstructionSheetData'
        Response:
          $ref: '#/components/schemas/200 UpdateResponse'
    InstructionSheet DeleteResult:
      type: object
      properties:
        Data:
          $ref: '#/components/schemas/InstructionSheetData'
        Response:
          $ref: '#/components/schemas/200 DeletedResponse'
